### ISSUE TITLE
Computing likelihood after fitting the model seems take a lot of memory

### ISSUE THREAD

**Issue by Jasonleng** [lnccbrown/HSSM#247]
Not a bug but when I fit a big model and set
```
idata_kwargs=dict(log_likelihood=True)
``` 
the fitting process goes well but sometimes the kernel is killed because out of memory after the code is computing the likelihood. I set the memory to 16G per core. Just curious if this is normal or if something to be fixed.

**Comment by AlexanderFengler** [comment]
Could you provide a few more details about your situation to help us locate the problem?
How big is your dataset, how many samples are you running, which type of likelihood?

One option is to use `pm.sample()` without returning the likelihoods first, and then compute the likelihood after (potentially on a thinned sample).

In general I have seen this outside of HSSM in pymc before.. The likelihood terms, since they are trial-wise, can blow up quite easily.

**Comment by Jasonleng** [comment]
> Could you provide a few more details about your situation to help us locate the problem? How big is your dataset, how many samples are you running, which type of likelihood?
> 
> One option is to use `pm.sample()` without returning the likelihoods first, and then compute the likelihood after (potentially on a thinned sample).
> 
> In general I have seen this outside of HSSM in pymc before.. The likelihood terms, since they are trial-wise, can blow up quite easily.

The dataset is ~24000 trials with 32 subjects. I'm running 1000 samples with 9000 burned. And it's approx_differentiable.

I will try your suggestion, separating the sample and likelihood calculation.

**Comment by digicosmos86** [comment]
This is fixed in #265. This is an oversight with older PyMC versions. The dev version of HSSM uses a newer version of PyMC, which will be included in the next release of HSSM as well.
