### ISSUE TITLE
Uninformative Traces and Extremely High R-Hat Values

### ISSUE THREAD

**Issue by tooweisiannn** [lnccbrown/HSSM#338]
I am fitting a model with many interaction effects, and when I run the following code, none of the traces seem to vary at all (i.e horizontal line) and the model doesn't converge (rhat `4.7e+15`):

```
param_v = { #drift rate
    "name": "v",
    "formula" : "rt | dec(Resp) ~ Stim * SS * RI * Age * Condition + (1|participant_id)",
    "link": "identity"
}

param_a = { #boundary seperation
    "name": "a",
    "prior": {
        "a": {"name": "Normal", "mu": 0.5, "sigma": 0.2}
        },
    "formula" : "a ~ SS * RI * Age * Condition + (1|participant_id)",
    "link": "log"
}

param_z = { #bias
    "name": "z", 
    "prior": {
        "z": {"name": "Normal", "mu": 0.5, "sigma": 0.2}
        },
    "formula": "z ~ SS * RI * Age * Condition + (1|participant_id)",
    "link": "log"
}

param_t = { #ndt
    "name": "t",
    "prior": {
        "Intercept": {"name": "Uniform", "initval": -3}
        },
    "formula" : "t ~ Age * Condition + (1|participant_id)",
    "link": "logit"

}

ddm = hssm.HSSM(data=dat,
                model="ddm",
                include = [
                    param_v,
                    param_a,
                    param_z,
                    param_t
                ],
) 

config.update("jax_enable_x64", False)

infer_ddm = ddm.sample(
    sampler = "nuts_numpyro",
    chains = 5,
    cores = 3,
    draws = 5000,
    tune = 2000,
)
```

Here are the traces:

 
![image](https://github.com/lnccbrown/HSSM/assets/111456925/7190a89b-8eaa-4caa-9972-93dc88b9e1c5)

Where it seems like nothing is going on in the trace. Additionally, my sampling does not take a very long time ~5 minutes, but the when I try `az.summary(infer_ddm)`, the summary table takes over 40 minutes to run.

I would appreciate any help.

Thanks

**Comment by digicosmos86** [comment]
Hi @tooweisiannn!

Thanks for letting us know about this issue! There are other folks on the team that are more knowledgeable than me about hierarchical models with multiple interactions. I just wanted to point out some of the issues in the parameter specification:

```python
param_v = { #drift rate
    "name": "v",
    "formula" : "rt | dec(Resp) ~ Stim * SS * RI * Age * Condition + (1|participant_id)",
    "link": "identity"
}

param_a = { #boundary seperation
    "name": "a",
    "prior": {
        "a": {"name": "Normal", "mu": 0.5, "sigma": 0.2}
        },
    "formula" : "a ~ SS * RI * Age * Condition + (1|participant_id)",
    "link": "log"
}

param_z = { #bias
    "name": "z", 
    "prior": {
        "z": {"name": "Normal", "mu": 0.5, "sigma": 0.2}
        },
    "formula": "z ~ SS * RI * Age * Condition + (1|participant_id)",
    "link": "log"
}

param_t = { #ndt
    "name": "t",
    "prior": {
        "Intercept": {"name": "Uniform", "initval": -3}
        },
    "formula" : "t ~ Age * Condition + (1|participant_id)",
    "link": "logit"
}
```

First, the response variable of your `v` parameter is not `v`. Internally, `hssm` will disregard the left side of the first parameter with a regression. So if you need some transformation in the response, we recommend that you do the transformation before constructing the `HSSM` model.

Second, for `a` and `z` parameters, it seems that your priors are set for `a` and `z`? We recommend that you set the prior on the individual covariates in the regression. The more specific, the better, because the current defaults might cause the analytical likelihood function to misbehave.

Also the choice of link functions seem a bit strange. `z`, for example, is defined on (0, 1), and the `log` link function only transforms the results of the regression to (0, inf), which can cause the likelihood function to misbehave as well.

These are just a few issues that stand out to me in terms of model specification. I defer to my teammates for more details about the model itself. We are also rolling out a new version that has better default prior specification in a few days that might help as well. Please stay tuned!

Thanks,
Paul

**Comment by tooweisiannn** [comment]
Hi Paul,

I appreciate the quick response! I will try these suggestions.

Thanks

**Comment by digicosmos86** [comment]
Close for now. Please feel free to reopen if you still run into the same issue
