### ISSUE TITLE
Using NumPy C-API based implementation for BLAS functions

### ISSUE THREAD

**Issue by dmd** [lnccbrown/HSSM#341]
I'm at my wit's end trying to get past this:

```
>>> import hssm
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

I have already read #204 and did not see anything useful in it.

Here is how I installed:

```
conda create -n hssm python=3.11
conda activate hssm
pip install git+https://github.com/lnccbrown/HSSM.git
```

I am on RHEL 8. I have `blas`, `blas-devel`, `openblas`, and `openblas-devel` packages installed. I have `g++` installed.

What am I missing?

**Comment by dmd** [comment]
(By the way, is there a Docker for HSSM? That would solve a lot of the problems people have with getting it to work...)

**Comment by AlexanderFengler** [comment]
Hi @dmd ,
 
Concerning your question, can you try to use a conda install of pymc before installing hssm?
One issue here is that the PyMC developers are banking pretty heavily on conda infrastructure, so PyMC pip installs generally end up more finicky.

This is a bit annoying for us since we would like to keep HSSM pip installable (without extra leg work), and we are bringing this up to PyMC core, but we will also try to set up a conda install for HSSM to clean up installation problems asap (winter break is ending as we speak :)). 

Setting up a docker is also a good suggestion and already on our todo as well.

**Comment by dmd** [comment]
That seems to have worked!

**Comment by dmd** [comment]
Actually, this is bizarre. It works *as root*, but not for ordinary users, and I can't figure out why.

If I do the install as an ordinary user - whether in conda or a plain python venv, I still get the warning - whether or not I install `pymc` first in the venv.
