### ISSUE TITLE
Parallel for HDDM's `find_starting_values()` in HSSM

### ISSUE THREAD

**Issue by jainraj** [lnccbrown/HSSM#410]
The HDDM library has a method called `find_starting_values()`, which apparently helps if parameters don't converge (I never used HDDM personally, so I can only assume). 

I am wondering: 
- Is there a similar method in the HSSM library?
- If not, are you planning to build one? 
- If not, what are the constraints? Is HSSM so general that such a method may not ever exist?

**Comment by AlexanderFengler** [comment]
`find_starting_values()` basically ran the equivalent of `find_MAP()` in PyMC, to initialize the chains. Initializing chains with MAP values is discouraged from a theoretical viewpoint, however we are thinking of adding this feature again because in practice it can de facto help. 

However by "adding this feature" I just mean creating a convenience wrapper around manually calling `myhssmmodel.pymc_model.find_MAP()` and assigning the results as starting values to the chains, which you can in principle do already.

**Comment by jainraj** [comment]
Awesome! Thanks for this!
